# This is version R00 of the training configuration
# Using PPO
behaviors:
  ConfigurablePart:
    trainer_type: ppo
    max_steps: 500000
    time_horizon: 64
    summary_freq: 1000
    checkpoint_interval: 5000
    hyperparameters:
      learning_rate: 3.0e-4
      batch_size: 32
      buffer_size: 2048
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encoder_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0