# This is version R00 of the training configuration
# Using SAC
behaviors:
  ConfigurablePart:
    trainer_type: sac
    hyperparameters:
      batch_size: 128
      buffer_size: 128000
      buffer_init_steps: 2000
      init_entcoef: 0.05
      steps_per_update: 1
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    max_steps: 500000
    time_horizon: 64
    summary_freq: 1000