behaviors:
  ConfigurablePart:
    trainer_type: sac
    hyperparameters:
      batch_size: 64
      buffer_size: 64000
      buffer_init_steps: 1000
      init_entcoef: 0.1
      steps_per_update: 1
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000